Insensitive language: replace whitelist with allowlist
box/boxcli pull request #247
Opened 2021-06-09 17:38 UTC by mhagmajer

Note this also bump `box-node-sdk` dependency to `^1.37.2` to depend on the version after the insensitive language scan fixes.

2021-06-14 17:10 UTC, sujaygarlanka requested changes
If we delete the collaboration-whitelist commands, the CLI will no longer be backwards compatible. We should leave these in and add deprecation tags.

2021-06-17 14:04 UTC, mhagmajer commented on src/commands/collaboration-whitelist/index.js
> +CollaborationWhitelistListCommand.hidden = true;
Thanks @sujaygarlanka. I restored `box collaboration-whitelist` to be exactly like `box collaboration-allowlist` except it won't show in the list of commands as it is hidden.

2021-06-17 14:55 UTC, sujaygarlanka approved these changes

2021-06-18 14:01 UTC, merged

2021-06-18 14:02 UTC, mhagmajer commented
Thanks for the review @sujaygarlanka!